#ifndef _PRIORITY_H_
#define _PRIORITY_H_

#define CLOCKSERVER_PRIORITY    1
#define CLOCKNOTIFIER_PRIORITY  0

#define NAMESERVER_PRIORITY     2

#define IDLE_TASK_PRIORITY 31

#define TERMINAL_SERVER_PRIORITY 2
#define TERMINAL_NOTIFIER_PRIORITY 1
#define TERMINAL_COURIER_PRIORITY 2

#define TRAIN_SERVER_PRIORITY 2
#define TRAIN_NOTIFIER_PRIORITY 1

#endif
